name: test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: style
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .
      - name: install neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable
      - name: get VIMRUNTIME
        id: vimruntime
        run: echo "path=$(nvim --headless --cmd 'echo $VIMRUNTIME' +q 2>&1)" >> $GITHUB_OUTPUT
      - name: types
        uses: mrcjkb/lua-typecheck-action@v1.1.0
        env:
          VIMRUNTIME: ${{ steps.vimruntime.outputs.path }}
        with:
          checklevel: Hint
          configpath: ".luarc.json"
          directories: |
            lua
            spec

  test:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: install neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable
      - name: install lua
        uses: leafo/gh-actions-lua@v12
        with:
          luaVersion: "5.1.5"
      - name: install luarocks
        uses: leafo/gh-actions-luarocks@v6
      - name: setup luarocks project
        run: luarocks init --local
      - name: test
        run: |
          eval $(luarocks path)
          luarocks test
